# Generated by Django 4.2.4 on 2023-10-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
