# Generated by Django 4.2.4 on 2023-10-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadscontent',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
