# Generated by Django 4.2.4 on 2023-10-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_threadscontent_no_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
