# Generated by Django 4.2.4 on 2023-10-31 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerscount',
            name='follower',
        ),
        migrations.AddField(
            model_name='followerscount',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='followerscount',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threadscontent',
            name='content_img',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/'),
        ),
        migrations.AlterField(
            model_name='followerscount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
