# Generated by Django 4.2.4 on 2023-11-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadscontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
