# Generated by Django 4.2.4 on 2023-11-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_threadscontent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
