# Generated by Django 4.2.4 on 2023-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='you_like_this',
            field=models.BooleanField(default=False),
        ),
    ]
