# Generated by Django 4.2.4 on 2023-11-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_followersmanager_delete_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadscontent',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
