# Generated by Django 4.2.4 on 2023-11-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_threadscontent_content_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default/default_image.png', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='threadscontent',
            name='content_img',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/'),
        ),
    ]
